services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "aiharmony"
    ports:
      - "1433:1433"
    volumes:
      - ./mssql/init.sql:/scripts/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"aiharmony\" -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
     